name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]
    paths:
      - 'public/config.json'
      - 'public/version.txt'
      - 'firebase.json'
      - '.firebaserc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: testconfigs-c3b83
          channelId: live
